<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1259" started-at="2018-07-27T13:58:40Z" finished-at="2018-07-27T13:58:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1259" started-at="2018-07-27T13:58:40Z" finished-at="2018-07-27T13:58:41Z">
      <class name="com.flipkart.testScripts.FlipKartTestCase">
        <test-method status="PASS" signature="setup(org.testng.ITestContext)[pri:0, instance:com.flipkart.testScripts.FlipKartTestCase@1d4f8f5]" name="setup" is-config="true" duration-ms="246" started-at="2018-07-27T13:58:40Z" finished-at="2018-07-27T13:58:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@12c0e88]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="FlipKart_TC1(java.lang.String)[pri:0, instance:com.flipkart.testScripts.FlipKartTestCase@1d4f8f5]" name="FlipKart_TC1" duration-ms="125" started-at="2018-07-27T13:58:41Z" data-provider="FlipKartTestData" finished-at="2018-07-27T13:58:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[userName~9849530029
password~satish@123]]>
              </value>
            </param>
          </params>
          <exception class="com.flipkart.utilities.MyOwnException">
            <message>
              <![CDATA[Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null
]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.flipkart.utilities.MyOwnException: Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null

at com.flipkart.accelarators.Base.throwException(Base.java:208)
at com.flipkart.testScripts.FlipKartTestCase.FlipKart_TC1(FlipKartTestCase.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.flipkart.utilities.MyOwnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlipKart_TC1 -->
        <test-method status="PASS" signature="close(org.testng.ITestContext)[pri:0, instance:com.flipkart.testScripts.FlipKartTestCase@1d4f8f5]" name="close" is-config="true" duration-ms="11" started-at="2018-07-27T13:58:41Z" finished-at="2018-07-27T13:58:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@12c0e88]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="FAIL" signature="afterExecutionOfEachTest(java.lang.reflect.Method, org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.flipkart.testScripts.FlipKartTestCase@1d4f8f5]" name="afterExecutionOfEachTest" is-config="true" duration-ms="0" started-at="2018-07-27T13:58:41Z" finished-at="2018-07-27T13:58:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.flipkart.testScripts.FlipKartTestCase.FlipKart_TC1(java.lang.String) throws java.lang.InterruptedException,com.flipkart.utilities.MyOwnException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@12c0e88]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[[TestResult name=FlipKart_TC1 status=FAILURE method=FlipKartTestCase.FlipKart_TC1(java.lang.String)[pri:0, instance:com.flipkart.testScripts.FlipKartTestCase@1d4f8f5] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="com.flipkart.utilities.MyOwnException">
            <message>
              <![CDATA[AFTER METHOD IS NOT SUCCESSFUL
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.flipkart.utilities.MyOwnException: AFTER METHOD IS NOT SUCCESSFUL
null
at com.flipkart.accelarators.Base.throwException(Base.java:208)
at com.flipkart.testScripts.FlipKartTestCase.afterExecutionOfEachTest(FlipKartTestCase.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.flipkart.utilities.MyOwnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterExecutionOfEachTest -->
      </class> <!-- com.flipkart.testScripts.FlipKartTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
