<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SSS-PC" name="com.flipkart.testScripts.MultiBrowserTestCase3" tests="2" failures="0" timestamp="24 Jul 2018 03:21:36 GMT" time="28.627" errors="2">
  <testcase name="FlipKart_TC1" time="18.670" classname="com.flipkart.testScripts.MultiBrowserTestCase3">
    <error type="com.flipkart.utilities.MyOwnException" message="Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null value in entry: url=null
">
      <![CDATA[com.flipkart.utilities.MyOwnException: Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null value in entry: url=null

at com.flipkart.accelarators.Base.throwException(Base.java:208)
at com.flipkart.testScripts.MultiBrowserTestCase3.FlipKart_TC1(MultiBrowserTestCase3.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- FlipKart_TC1 -->
  <testcase name="FlipKart_TC1" time="9.957" classname="com.flipkart.testScripts.MultiBrowserTestCase3">
    <error type="com.flipkart.utilities.MyOwnException" message="Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null value in entry: url=null
">
      <![CDATA[com.flipkart.utilities.MyOwnException: Login SUCCESSFUL
UNABLE TO INITIATE THE login PROCESS 
null value in entry: url=null

at com.flipkart.accelarators.Base.throwException(Base.java:208)
at com.flipkart.testScripts.MultiBrowserTestCase3.FlipKart_TC1(MultiBrowserTestCase3.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- FlipKart_TC1 -->
</testsuite> <!-- com.flipkart.testScripts.MultiBrowserTestCase3 -->
